name: JSDocs
on: push
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: install modules
          working-directory: ./scripts
          run: npm install documentation
          
        - name: Build
          run: documentation build ./scripts/script.js -f md
      
          
      

