name: JSDocs
on: push
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Build
          uses: andstor/jsdoc-action@v1
          with:
            source_dir: ./scripts
            recurse: true
            output_dir: ./scripts
      
        - name: list
          working-directory: ./scripts
          run: ls
               cat index.html
               cat styles


