name: JSDocs
on: push
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Build
          uses: andstor/jsdoc-action@v1
          with:
            source_dir: ./scripts
            recurse: true
            output_dir: ./jsdocs
        
        - name: branch check 
          run: git branch
            
        - name: config b2wu
          working-directory: ./
          run: |
            
            git config --global user.name "QE" 
            git config --global user.email "b2wu@ucsd.edu"
            git add jsdocs/
            git commit -m 'jsodcs updatge'
            git push origin k1:main
          
