name: JSDocs
on: push
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Build
          uses: andstor/jsdoc-action@v1
          with:
            source_dir: ./scripts
            recurse: true
            output_dir: ./jsdocs
      


        - name: upload to repor
          working-directory: ./
          run: git add jsdocs/
        - name: commit to repor
          run: git commit 'jsodcs updatge'
        - name: push to repor
          run: git push origin master
          
